pipeline:
  identifier: Build_java_1717593287692
  name: Build java
  orgIdentifier: default
  projectIdentifier: justalab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.wojciehmgithub
        repoName: java
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
